export const CHANGE_EDIT_STATUS_CLASS= 'CHANGE_EDIT_STATUS_CLASS'
export const FETCH_DATABASE_FEATURED_PRODUCTS = 'FETCH_DATABASE_FEATURED_PRODUCTS'
export const FETCH_DATABASE_ALL_PRODUCTS = 'FETCH_DATABASE_ALL_PRODUCTS'
export const GET_PRICE_FILTER = 'GET_PRICE_FILTER'
export const GET_DATA_FILTER = 'GET_DATA_FILTER'
export const CHANGE_EDIT_STATUS_CLASS_SIDEBAR= 'CHANGE_EDIT_STATUS_CLASS_SIDEBAR'
export const GET_TEXT_SEARCH_FILTER= 'GET_TEXT_SEARCH_FILTER'

//cart
export const ADD_TO_CART= 'ADD_TO_CART'
export const CHANGE_MESSAGE= 'CHANGE_MESSAGE'
export const DELETE_PRODUCT_IN_CART= 'DELETE_PRODUCT_IN_CART'
export const UPDATE_PRODUCT_IN_CART= 'UPDATE_PRODUCT_IN_CART'

