export const MSG_ADD_TO_CART_SUCCESS =" Mua hang thanh cong"
export const MSG_UPDATE_TO_CART_SUCCESS =" Cap nhat hang thanh cong"
export const MSG_DELETE_TO_CART_SUCCESS =" Xoa hang thanh cong"
export const MSG_CART_EMPTY =" Chua co san pham nao trong gio hang"
export const MSG_WELCOME =" Chao mung den voi Dynamite Shop"
